package com.bookstore.entity;
// Generated Sep 25, 2021 10:34:50 AM by Hibernate Tools 5.2.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Contact generated by hbm2java
 */
@Entity
@NamedQueries({
	@NamedQuery(name = "Contact.findAll", query = "select c from Contact c order by c.contactDate desc")
})
@Table(name = "contact", catalog = "bookstoredb")
public class Contact implements java.io.Serializable {

	private Integer contactId;
	private String name;
	private String email;
	private String title;
	private String description;
	private Date contactDate;

	public Contact() {
	}

	public Contact(String name, String email, String title, String description, Date contactDate) {
		this.name = name;
		this.email = email;
		this.title = title;
		this.description = description;
		this.contactDate = contactDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "contact_id", unique = true, nullable = false)
	public Integer getContactId() {
		return this.contactId;
	}

	public void setContactId(Integer contactId) {
		this.contactId = contactId;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "email", nullable = false, length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "title", nullable = false, length = 128)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "description", nullable = false, length = 16777215)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "contact_date", nullable = false, length = 19)
	public Date getContactDate() {
		return this.contactDate;
	}

	public void setContactDate(Date contactDate) {
		this.contactDate = contactDate;
	}

}
