package com.bookstore.entity;
// Generated Sep 14, 2021 3:25:25 PM by Hibernate Tools 5.2.10.Final

import java.util.Base64;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.persistence.UniqueConstraint;

/**
 * News generated by hbm2java
 */
@Entity
@NamedQueries({
	@NamedQuery(name = "News.findAll", query = "select n from News n"),
	@NamedQuery(name = "News.findByTitle", query = "select n from News n where n.title = :title"),
	@NamedQuery(name = "News.listNew", query = "select n from News n order by n.publishDate desc") ,
	@NamedQuery(name = "News.countAll", query = "select count(*) from News n"),
	@NamedQuery(name = "News.indexNew", query = "select n from News n order by n.publishDate desc") 
})
@Table(name = "news", catalog = "bookstoredb", uniqueConstraints = @UniqueConstraint(columnNames = "title"))
public class News implements java.io.Serializable {

	private Integer newId;
	private String title;
	private String author;
	private String content;
	private byte[] image;
	private String base64Image;
	private Date publishDate;

	public News() {
	}
	
	public News(Integer newId) {
		super();
		this.newId = newId;
	}

	public News(String title, String author, String content, byte[] image, Date publishDate) {
		this.title = title;
		this.author = author;
		this.content = content;
		this.image = image;
		this.publishDate = publishDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "new_id", unique = true, nullable = false)
	public Integer getNewId() {
		return this.newId;
	}

	public void setNewId(Integer newId) {
		this.newId = newId;
	}

	@Column(name = "title", unique = true, nullable = false, length = 128)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "author", nullable = false, length = 64)
	public String getAuthor() {
		return this.author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

	@Column(name = "content", nullable = false, length = 16777215)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "image", nullable = false)
	public byte[] getImage() {
		return this.image;
	}

	public void setImage(byte[] image) {
		this.image = image;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "publish_date", nullable = false, length = 10)
	public Date getPublishDate() {
		return this.publishDate;
	}

	public void setPublishDate(Date publishDate) {
		this.publishDate = publishDate;
	}
	
	@Transient
	public String getBase64Image() {
		this.base64Image = Base64.getEncoder().encodeToString(this.image);
		return this.base64Image;
	}

	@Transient
	public void setBase64Image(String base64Image) {
		this.base64Image = base64Image;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		News other = (News) obj;
		if (newId == null) {
			if (other.newId != null)
				return false;
		} else if (!newId.equals(other.newId))
			return false;
		return true;
	}
	
	
}
